name = "Create Feral Engines Aero"
author = "_Zaraman3_"
version = "0.7.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ad9c03839a7a86c61fabd5938398f89356356b5b857deb1d7d8c0662bcfaa4b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
