name = "Create Feral Engines Aero"
author = "_Zaraman3_"
version = "0.7.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37d975490df68fe6c3f66dd6b8d85c5b2eb63826f7bcf27d68c12f04a046b5ba"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
