name = "Create Feral Engines Aero"
author = "_Zaraman3_"
version = "0.7.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "822d64168a35c0a7355a7cf2cde0ada8b537c77b79746ed0e525c6c45052aae2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
